import type { Lever } from "./types";

export const LEVERS: Lever[] = [
  {
    id: "field-force-expansion",
    category: "commercial-investment",
    displayName: "Field Force Expansion",
    description: "Add net new sales reps to expand call coverage on target accounts.",
    unitOfInvestment: "rep-year",
    minIntensity: 1,
    maxIntensity: 30,
    unitCostUsd: 280_000,
    elasticityShape: "logarithmic",
    elasticityParams: {
      baselineImpact: 0.0005,
      saturationImpact: 0.011,
      decayRate: 0.12,
    },
    rampWeeks: 12,
    durationWeeks: 52,
    riskScore: "medium",
    benchmarkSource: "ZS Associates 2023 sales force productivity benchmarks for specialty pharma",
  },
  {
    id: "field-force-reallocation",
    category: "commercial-optimization",
    displayName: "Field Force Reallocation",
    description: "Shift existing reps from low-elasticity to high-elasticity territories.",
    unitOfInvestment: "rep-month-shifted",
    minIntensity: 1,
    maxIntensity: 60,
    unitCostUsd: 4_500,
    elasticityShape: "logarithmic",
    elasticityParams: {
      baselineImpact: 0.0004,
      saturationImpact: 0.006,
      decayRate: 0.18,
    },
    rampWeeks: 4,
    durationWeeks: 26,
    riskScore: "low",
    benchmarkSource: "IQVIA Channel Dynamics 2023 — territory realignment ROI study",
  },
  {
    id: "sample-allocation",
    category: "commercial-optimization",
    displayName: "Sample Reallocation",
    description: "Concentrate physician samples on high-conversion accounts.",
    unitOfInvestment: "$M sample-budget-shifted",
    minIntensity: 0.5,
    maxIntensity: 8,
    unitCostUsd: 1_000_000,
    elasticityShape: "s-curve",
    elasticityParams: {
      baselineImpact: 0.0002,
      saturationImpact: 0.005,
      midpoint: 2.0,
      steepness: 0.5,
    },
    rampWeeks: 6,
    durationWeeks: 26,
    riskScore: "low",
    benchmarkSource: "Komodo Sample-to-NBRx conversion benchmarks 2023, MS therapeutic area",
  },
  {
    id: "patient-services-capacity",
    category: "operations-investment",
    displayName: "Patient Services Capacity",
    description: "Expand hub services to compress enrollment-to-first-infusion timeline.",
    unitOfInvestment: "$M patient-services-headcount",
    minIntensity: 1,
    maxIntensity: 12,
    unitCostUsd: 1_000_000,
    elasticityShape: "capacity-bounded",
    elasticityParams: {
      baselineImpact: 0.0007,
      saturationImpact: 0.006,
      capacityThreshold: 6,
    },
    rampWeeks: 8,
    durationWeeks: 52,
    riskScore: "low",
    benchmarkSource: "Genentech-comparable specialty hub operations benchmark, 2023",
  },
  {
    id: "dtc-spend",
    category: "commercial-investment",
    displayName: "DTC Awareness Campaign",
    description: "Direct-to-consumer awareness investment in target geographies.",
    unitOfInvestment: "$M DTC-spend",
    minIntensity: 2,
    maxIntensity: 20,
    unitCostUsd: 1_000_000,
    elasticityShape: "s-curve",
    elasticityParams: {
      baselineImpact: 0.000,
      saturationImpact: 0.006,
      midpoint: 5,
      steepness: 0.2,
    },
    rampWeeks: 14,
    durationWeeks: 26,
    riskScore: "high",
    benchmarkSource: "Nielsen DTC effectiveness study 2023, MS therapeutic category",
  },
  {
    id: "account-targeting",
    category: "commercial-optimization",
    displayName: "Account Targeting Refinement",
    description: "Tighten targeting to top-30 accounts vs broad coverage.",
    unitOfInvestment: "$M targeting-program-investment",
    minIntensity: 0.5,
    maxIntensity: 4,
    unitCostUsd: 1_000_000,
    elasticityShape: "logarithmic",
    elasticityParams: {
      baselineImpact: 0.0012,
      saturationImpact: 0.0045,
      decayRate: 0.5,
    },
    rampWeeks: 4,
    durationWeeks: 26,
    riskScore: "low",
    benchmarkSource: "IDN account targeting program ROI benchmarks, MS specialty therapeutics",
  },
];

export function getLever(id: string): Lever | undefined {
  return LEVERS.find((l) => l.id === id);
}
